"""
Django settings for UnidadMedica project.

Generated by 'django-admin startproject' using Django 5.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os
from dotenv import load_dotenv

# Cargar variables de entorno desde .env
load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv('SECRET_KEY', 'django-insecure--kk8_by0(=pz_y_k33gfx231bh!8owr+n76j=n$bggod93d7m2')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv('DEBUG', 'True') == 'True'

ALLOWED_HOSTS = os.getenv('ALLOWED_HOSTS', '').split(',') if os.getenv('ALLOWED_HOSTS') else []


# Application definition

INSTALLED_APPS = [   
    'jazzmin', 
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    
    'web',
    'citas',
]

# Configuración de archivos estáticos
STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'static'),
]

# Configuración de archivos multimedia
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# Configuración de archivos estáticos para desarrollo
if DEBUG:
    STATICFILES_DIRS = [
        os.path.join(BASE_DIR, 'static'),
    ]
else:
    STATIC_ROOT = os.path.join(BASE_DIR, 'static')

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'UnidadMedica.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'UnidadMedica.wsgi.application'


# Configuración de zona horaria
TIME_ZONE = 'America/Caracas'
USE_TZ = True

# Configuración de formato de fechas
DATE_INPUT_FORMATS = [
    '%Y-%m-%d',  # '2006-10-25'
    '%d/%m/%Y',  # '25/10/2006'
    '%d/%m/%y',  # '25/10/06'
]

DATETIME_INPUT_FORMATS = [
    '%Y-%m-%d %H:%M:%S',     # '2006-10-25 14:30:59'
    '%Y-%m-%d %H:%M',        # '2006-10-25 14:30'
    '%d/%m/%Y %H:%M:%S',     # '25/10/2006 14:30:59'
    '%d/%m/%Y %H:%M',        # '25/10/2006 14:30'
    '%d/%m/%y %H:%M:%S',     # '25/10/06 14:30:59'
    '%d/%m/%y %H:%M',        # '25/10/06 14:30'
]

# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': os.getenv('DB_NAME', 'unidad_medica'),
        'USER': os.getenv('DB_USER', 'postgres'),
        'PASSWORD': os.getenv('DB_PASSWORD', ''),
        'HOST': os.getenv('DB_HOST', 'localhost'),
        'PORT': os.getenv('DB_PORT', '5432'),
        'OPTIONS': {
            'options': '-c search_path=public',
            'client_encoding': 'UTF8',
            'connect_timeout': 5,
        },
        'CONN_MAX_AGE': 300,
        'DISABLE_SERVER_SIDE_CURSORS': True,
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

LOGIN_REDIRECT_URL = 'web:inicio'
LOGOUT_REDIRECT_URL = 'web:inicio'
# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'es'

TIME_ZONE = 'America/Caracas'

USE_I18N = True
USE_L10N = True
USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = '/static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Directorios de archivos estáticos (Django buscará aquí CSS, JS, imágenes)
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'static'),
]

JAZZMIN_SETTINGS = {
    # -------------------------------------------------------------------------
    # CONFIGURACIÓN GENERAL
    # -------------------------------------------------------------------------
    "site_title": "Unidad Médica Admin",
    "site_header": "Unidad Médica",
    "site_brand": "UM",
    "site_logo": "img/favicon.png",
    "site_icon": "img/favicon.png",
    
    # Personalización del login
    "login_logo": None,
    "login_logo_dark": None,
    "login_image": None,
    "welcome_sign": "Bienvenido al Sistema de Gestión Médica",
    "show_ui_builder": True,
    
    # Personalización de la barra superior
    "topmenu_links": [
        {"name": "Inicio", "url": "admin:index", "permissions": ["auth.view_user"]},
        {"name": "Sitio Web", "url": "/", "new_window": True},
    ],
    
    # Personalización del menú lateral
    #"custom_css": "css/admin_custom.css",
    
    # -------------------------------------------------------------------------
    # ESTRUCTURA DEL MENÚ JERÁRQUICO MULTINIVEL
    # -------------------------------------------------------------------------
    "menu": [
    # -----------------------------------------------------------------
    # 1. INICIO
    # -----------------------------------------------------------------
    {
        "name": "Inicio",
        "url": "/admin/",
        "icon": "fas fa-home",
        "permissions": ["auth.view_user"]
    },
    
    # -----------------------------------------------------------------
    # 2. AGENDA Y CITAS (Operacional)
    # -----------------------------------------------------------------
    {
        "name": "Agenda y Citas",
        "icon": "fas fa-calendar-check",
        "app": "citas",
        "permissions": ["citas.view_cita"],
        "models": [
            {
                "name": "Calendario",
                "url": "/citas/calendario/",
                "icon": "fas fa-calendar-day"
            },
            {
                "name": "Gestión de Citas",
                "icon": "fas fa-calendar-plus",
                "models": [
                    {"name": "Lista de Citas", "model": "citas.cita", "icon": "fas fa-list"},
                    {"name": "Tipos de Cita", "model": "citas.tipocita", "icon": "fas fa-tags"},
                    {"name": "Estados de Cita", "model": "citas.estadocita", "icon": "fas fa-tag"}
                ]
            }
        ]
    },
    
    # -----------------------------------------------------------------
    # 3. GESTIÓN MÉDICA Y PERSONAL (Usuarios y Expedientes)
    # -----------------------------------------------------------------
    {
        "name": "Gestión Médica",
        "icon": "fas fa-hospital-user",
        "app": "citas",
        "permissions": ["citas.view_paciente", "citas.view_usuariomedico"],
        "models": [
            # Submenú Pacientes
            {
                "name": "Pacientes",
                "icon": "fas fa-user-injured",
                "permissions": ["citas.view_paciente"],
                "models": [
                    {"name": "Lista de Pacientes", "model": "citas.paciente", "icon": "fas fa-list"},
                    {"name": "Direcciones", "model": "citas.direccionpaciente", "icon": "fas fa-address-book"},
                    {"name": "Grupos Familiares", "model": "citas.familia"},
                    {"name": "Parentescos", "model": "citas.parentesco"}
                ]
            },
            
            # Submenú Médicos y Especialidades
            {
                "name": "Médicos y Horarios",
                "icon": "fas fa-user-md",
                "permissions": ["citas.view_usuariomedico"],
                "models": [
                    {"name": "Lista de Médicos", "model": "citas.usuariomedico", "icon": "fas fa-list"},
                    {"name": "Horarios (Disponibilidad)", "model": "citas.horariocita", "icon": "fas fa-clock"}, 
                    {"name": "Días no Laborables", "model": "citas.dianolaborable", "icon": "far fa-calendar-times"},
                    {"name": "Especialidades por Médico", "url": "/citas/medico-especialidad/listar/", "icon": "fas fa-user-tag"}
                ]
            },
            
            # Submenú Consultas y Registros
            {
                "name": "Registros de Consultas",
                "icon": "fas fa-notes-medical",
                "permissions": ["citas.view_consulta"],
                "models": [
                    {"name": "Registros", "model": "citas.consulta"},
                    {"name": "Diagnósticos", "model": "citas.diagnostico"},
                    {"name": "Recetas", "model": "citas.receta"},
                    {"name": "Exámenes", "model": "citas.examen"}
                ]
            }
        ]
    },
    
    # -----------------------------------------------------------------
    # 4. ADMINISTRACIÓN Y CATÁLOGOS (Configuración, Geografía, Maestros)
    # -----------------------------------------------------------------
    {
        "name": "Administración y Catálogos",
        "icon": "fas fa-cogs",
        "permissions": ["auth.view_user", "sites.view_site"],
        "models": [
            {
                "name": "Seguridad y Usuarios",
                "icon": "fas fa-shield-alt",
                "models": [
                    {"name": "Usuarios", "model": "auth.user"},
                    {"name": "Grupos", "model": "auth.group"},
                    {"name": "Permisos", "model": "auth.permission"}
                ]
            },
            {
                "name": "Catálogos Médicos",
                "icon": "fas fa-hospital-symbol",
                "models": [
                    {"name": "Consultorios", "model": "citas.consultorio"},
                    {"name": "Especialidades", "model": "citas.especialidadmedica"},
                    {"name": "Subespecialidades", "model": "citas.subespecialidad"},
                    {"name": "Turnos", "model": "citas.turno"}
                ]
            },
            {
                "name": "Catálogos Geográficos",
                "icon": "fas fa-globe-americas",
                "models": [
                    {"name": "Países", "model": "citas.pais"},
                    {"name": "Estados", "model": "citas.estado"},
                    {"name": "Ciudades", "model": "citas.ciudad"},
                    {"name": "Municipios", "model": "citas.municipio"},
                    {"name": "Parroquias", "model": "citas.parroquia"}
                ]
            },
            {
                "name": "Otros Catálogos",
                "icon": "fas fa-database",
                "models": [
                    {"name": "Bancos", "model": "citas.banco"},
                    {"name": "Géneros (Sexo)", "model": "citas.sexo"},
                    {"name": "Estados Civiles", "model": "citas.estadocivil"}
                    # Tipos de Documento, Ocupaciones, Niveles de Instrucción eliminados por simplicidad
                ]
            },
            {
                "name": "Configuración del Sistema",
                "icon": "fas fa-sliders-h",
                "models": [
                    {"name": "Sitios", "model": "sites.site"},
                    {"name": "Parámetros", "model": "citas.parametro"},
                    {"name": "Notificaciones", "model": "citas.notificacion"}
                ]
            }
        ]
    }
],
    
    # -------------------------------------------------------------------------
    # CONFIGURACIÓN DE ÍCONOS, ORDEN Y OTROS (Se mantiene igual)
    # -------------------------------------------------------------------------
    "icons": {
    "auth": "fas fa-users-cog", "auth.user": "fas fa-user", "auth.Group": "fas fa-users", "auth.Permission": "fas fa-key", 
    "sites.Site": "fas fa-globe",
    "citas.Paciente": "fas fa-user-injured", 
    "citas.UsuarioMedico": "fas fa-user-md", 
    "citas.EspecialidadMedica": "fas fa-stethoscope", 
    "citas.Cita": "fas fa-calendar-check", 
    "": "fas fa-notes-medical", # Ícono del grupo Citas
    "citas.Prefijo_CIDNI": "fas fa-id-card", "citas.Sexo": "fas fa-venus-mars", 
    "citas.EstadoCivil": "fas fa-ring",
    "citas.Pais": "fas fa-globe-americas", "citas.Estado": "fas fa-map-marked-alt", 
    "citas.Ciudad": "fas fa-city", "citas.Municipio": "fas fa-map-signs", "citas.Parroquia": "fas fa-map-pin",
    "citas.Banco": "fas fa-university",
    "citas.HorarioCita": "fas fa-clock",
    "citas.Turno": "fas fa-clock",
    "citas.MedicoEspecialidad": "fas fa-user-md",
    "citas.Consultorio": "fas fa-hospital",
    # NOTA: Se eliminó el duplicado de citas.EspecialidadMedica y citas.DireccionPaciente (que no suele ser un ícono raíz)
},
    
  "order_with_respect_to": [
    # -----------------------------------------------------------------
    # 1. AUTENTICACIÓN Y ROLES (Lo primero para la gestión de usuarios)
    # -----------------------------------------------------------------
    "auth.user", 
    "auth.group",
    "auth.Permission", # Permisos (opcional, si es visible)
    
    # -----------------------------------------------------------------
    # 2. ROLES PRINCIPALES Y ASOCIACIONES
    # -----------------------------------------------------------------
    "citas.UsuarioMedico",         # Médicos (Usuario principal)
    "citas.Paciente",              # Pacientes
    
    # -----------------------------------------------------------------
    # 3. GESTIÓN DE CONSULTAS Y TIEMPO (Flujo Operacional)
    # -----------------------------------------------------------------
    "citas.HorarioCita",           # Horarios de los médicos
    "citas.Turno",                 # Turnos (Catálogo de apoyo para Horarios)
    "citas.Cita",                  # Citas (El modelo de agendamiento principal)
    "citas.Consultorio",           # Consultorios
    
    # -----------------------------------------------------------------
    # 4. ESPECIALIDADES Y DETALLES MÉDICOS
    # -----------------------------------------------------------------
    "citas.EspecialidadMedica",    # Catálogo de Especialidades
    "citas.MedicoEspecialidad",    # Relación Médico-Especialidad
    
    # -----------------------------------------------------------------
    # 5. CATÁLOGOS GEOGRÁFICOS (Datos estáticos y de Ubicación)
    # -----------------------------------------------------------------
    "citas.Pais",
    "citas.Estado",
    "citas.Ciudad",
    "citas.Municipio",
    "citas.Parroquia",
    
    # -----------------------------------------------------------------
    # 6. CATÁLOGOS MENORES/APOYO
    # -----------------------------------------------------------------
    "citas.EstadoCivil", 
    "citas.Prefijo_CIDNI", 
    "citas.Sexo",
    "citas.Banco",                 # Si es un modelo de apoyo
    
    # -----------------------------------------------------------------
    # 7. MODELOS DE SITIOS
    # -----------------------------------------------------------------
    "sites.Site",
    
    # Se añade el separador para el resto de modelos de la app "citas"
    "", 
],
    
    # El resto de la configuración se mantiene igual, ya que no afecta al menú:
    "usermenu_links": [
        {"name": "Soporte Técnico", "url": "https://github.com/farridav/django-jazzmin/issues", "new_window": True, "icon": "fas fa-life-ring"},
        {"name": "Documentación", "url": "https://django-jazzmin.com/", "new_window": True, "icon": "fas fa-book"},
    ],
    
    "theme": "cosmo",
    "dark_mode_theme": "darkly",
    "toggle_mode_btn": True,
    
    "copyright": "",
    "show_copyright": False,
    
    "navigation_expanded": True,
    "sidebar_fixed": True,
    "sidebar_nav_child_indent": True,
    "sidebar_nav_compact_style": True,
    
    "button_classes": {
        "primary": "btn-primary", "secondary": "btn-secondary", "info": "btn-info",
        "warning": "btn-warning", "danger": "btn-danger", "success": "btn-success"
    },
    
    "user_menu": {
        "show_all": True, "show_manage": False, "show_logout": True,
    },
    
    "changeform_format": "horizontal_tabs",
    "changeform_format_overrides": {
        "auth.user": "collapsible", "auth.group": "vertical_tabs"
    },
    
    "search_model": ["auth.User", "citas.Paciente", "citas.UsuarioMedico"],
}

# =========================================================================
# AJUSTES DE INTERFAZ (TWEAKS) - Mantenemos la indentación en True
# =========================================================================

JAZZMIN_UI_TWEAKS = {
    "navbar_small_text": False,
    "footer_small_text": False,
    "sidebar_show_apk_icons": True,
    "sidebar_user_small_text": False,
    "sidebar_disable_expand": False,
    # ESTO ES CRUCIAL PARA MOSTRAR EL MULTINIVEL
    "sidebar_nav_child_indent": True, 
    "sidebar_nav_compact_style": True,
    "sidebar_nav_legacy_style": False,
    "sidebar_nav_flat_style": False,
    "theme": "cosmo",
    "dark_mode_vars": {
        "primary": "#0d6efd", "secondary": "#6c757d", "info": "#17a2b8",
    },
    "body_small_text": False,
    "navbar_fixed": True,
    "footer_fixed": True, 
    "actions_fixed_top": True,
    
    "save_button_classes": "btn btn-success",
    "save_on_top": True, 
    "save_on_bottom": True,
    
    "content_padding": "5px",
    "sidebar_fixed": True,
}