# Generated by Django 5.2.7 on 2025-10-20 02:40

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ciudad',
            fields=[
                ('id_Ciudad', models.IntegerField(db_column='id_Ciudad', primary_key=True, serialize=False)),
                ('nombre', models.CharField(db_column='Ciudad', max_length=128, verbose_name='Ciudad')),
            ],
            options={
                'verbose_name': 'Ciudad',
                'verbose_name_plural': 'Ciudades',
                'db_table': 'ciudades',
                'ordering': ['nombre'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DireccionPaciente',
            fields=[
                ('id_Direccion_Paciente', models.AutoField(db_column='id_Direccion_Paciente', primary_key=True, serialize=False)),
                ('telefono', models.CharField(blank=True, db_column='Telefono', max_length=20, null=True, verbose_name='Teléfono Fijo')),
                ('celular', models.CharField(db_column='Celular', max_length=20, verbose_name='Teléfono Móvil')),
                ('correo', models.EmailField(blank=True, db_column='Correo', max_length=200, null=True, verbose_name='Correo Electrónico')),
                ('direccion', models.TextField(db_column='Direccion', verbose_name='Dirección Completa')),
                ('numero_casa', models.CharField(blank=True, db_column='Numero_Casa', max_length=50, null=True, verbose_name='Número de Casa/Apartamento')),
            ],
            options={
                'verbose_name': 'Dirección del Paciente',
                'verbose_name_plural': 'Direcciones de Pacientes',
                'db_table': 'direcciones_pacientes',
                'ordering': ['paciente__Apellidos_Paciente', 'paciente__Nombres_Paciente'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EspecialidadMedica',
            fields=[
                ('id_Especialidad_Medica', models.AutoField(primary_key=True, serialize=False, verbose_name='ID Especialidad')),
                ('Espacialidad_Medica', models.CharField(blank=True, max_length=200, null=True, verbose_name='Especialidad Médica')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('activa', models.BooleanField(default=True, verbose_name='¿Activa?')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Última Actualización')),
            ],
            options={
                'verbose_name': 'Especialidad Médica',
                'verbose_name_plural': 'Especialidades Médicas',
                'db_table': 'especialidades_medicas',
                'ordering': ['Espacialidad_Medica'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Estado',
            fields=[
                ('id_Estado', models.IntegerField(db_column='id_Estado', primary_key=True, serialize=False)),
                ('nombre', models.CharField(db_column='Estado', max_length=128, verbose_name='Estado')),
            ],
            options={
                'verbose_name': 'Estado',
                'verbose_name_plural': 'Estados',
                'db_table': 'estados',
                'ordering': ['nombre'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EstadoCivil',
            fields=[
                ('id_Estado_Civil', models.IntegerField(db_column='id_Estado_Civil', primary_key=True, serialize=False)),
                ('nombre', models.CharField(db_column='Estado_Civil', max_length=50, verbose_name='Estado Civil')),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Estado Civil',
                'verbose_name_plural': 'Estados Civiles',
                'db_table': 'estados_civiles',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Municipio',
            fields=[
                ('id_Municipio', models.IntegerField(db_column='id_Municipio', primary_key=True, serialize=False)),
                ('nombre', models.CharField(db_column='Municipio', max_length=128, verbose_name='Municipio')),
            ],
            options={
                'verbose_name': 'Municipio',
                'verbose_name_plural': 'Municipios',
                'db_table': 'municipios',
                'ordering': ['nombre'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id_Paciente', models.AutoField(primary_key=True, serialize=False)),
                ('Nombres_Paciente', models.CharField(max_length=200)),
                ('Apellidos_Paciente', models.CharField(max_length=100)),
                ('CIDNI', models.CharField(max_length=20)),
                ('Fecha_Nacimiento_Paciente', models.DateField()),
                ('Fecha_Registro', models.DateTimeField(default=django.utils.timezone.now)),
                ('Activo', models.BooleanField(default=True)),
                ('Ultima_Actualizacion', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Última Actualización')),
            ],
            options={
                'verbose_name': 'Paciente',
                'verbose_name_plural': 'Pacientes',
                'db_table': 'usuarios_pacientes',
                'ordering': ['Apellidos_Paciente', 'Nombres_Paciente'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Pais',
            fields=[
                ('id_Pais', models.IntegerField(db_column='id_Pais', primary_key=True, serialize=False)),
                ('nombre', models.CharField(db_column='Pais', max_length=128, verbose_name='País')),
                ('codigo', models.IntegerField(blank=True, db_column='Codigo', null=True, verbose_name='Código')),
            ],
            options={
                'verbose_name': 'País',
                'verbose_name_plural': 'Países',
                'db_table': 'paises',
                'ordering': ['nombre'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Parroquia',
            fields=[
                ('id_Parroquia', models.IntegerField(db_column='id_Parroquia', primary_key=True, serialize=False)),
                ('nombre', models.CharField(db_column='Parroquia', max_length=128, verbose_name='Parroquia')),
            ],
            options={
                'verbose_name': 'Parroquia',
                'verbose_name_plural': 'Parroquias',
                'db_table': 'parroquias',
                'ordering': ['nombre'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Prefijo_CIDNI',
            fields=[
                ('id_Prefijo_CIDNI', models.AutoField(db_column='id_Prefijo_CIDNI', primary_key=True, serialize=False)),
                ('nombre_prefijo', models.CharField(db_column='Prefijo_CIDNI', max_length=10)),
            ],
            options={
                'verbose_name': 'Prefijo CIDNI',
                'verbose_name_plural': 'Prefijos CIDNI',
                'db_table': 'prefijos_cedula',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Sexo',
            fields=[
                ('id_Sexo', models.IntegerField(db_column='id_Sexo', primary_key=True, serialize=False)),
                ('nombre', models.CharField(db_column='Sexo', max_length=20, verbose_name='Sexo')),
            ],
            options={
                'verbose_name': 'Sexo',
                'verbose_name_plural': 'Sexos',
                'db_table': 'sexos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MedicoEspecialidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Registro')),
                ('principal', models.BooleanField(default=False, verbose_name='Especialidad Principal')),
                ('activo', models.BooleanField(default=True, verbose_name='¿Activo?')),
                ('especialidad', models.ForeignKey(db_column='id_Especialidad_Medica', on_delete=django.db.models.deletion.CASCADE, to='citas.especialidadmedica')),
            ],
            options={
                'verbose_name': 'Especialidad del Médico',
                'verbose_name_plural': 'Especialidades de los Médicos',
                'db_table': 'medicos_especialidades',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='UsuarioMedico',
            fields=[
                ('id_Medico', models.AutoField(db_column='id_Medico', primary_key=True, serialize=False)),
                ('Nombres_Medico', models.CharField(db_column='Nombres_Medico', max_length=200, verbose_name='Nombres')),
                ('Apellidos_Medicos', models.CharField(db_column='Apellidos_Medicos', max_length=200, verbose_name='Apellidos')),
                ('CIDNI', models.CharField(db_column='CIDNI', max_length=20, verbose_name='Número de ID')),
                ('Fecha_Nacimiento_Medico', models.DateField(blank=True, db_column='Fecha_Nacimiento_Medico', null=True, verbose_name='Fecha de Nacimiento')),
                ('Registro_MPPS', models.CharField(blank=True, db_column='Registro_MPPS', max_length=30, null=True, verbose_name='Registro MPPS')),
                ('Numero_Colegio_de_Medico', models.CharField(blank=True, db_column='Numero_Colegio_de_Medico', max_length=50, null=True, verbose_name='N° Colegio de Médicos')),
                ('Foto_Medico', models.ImageField(blank=True, db_column='Foto_Medico', null=True, upload_to='medicos/fotos/', verbose_name='Fotografía')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Registro')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('telefono', models.CharField(blank=True, max_length=20, null=True, verbose_name='Teléfono')),
                ('email', models.EmailField(blank=True, max_length=100, null=True, verbose_name='Correo Electrónico')),
                ('Pais', models.ForeignKey(blank=True, db_column='Pais_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='citas.pais', verbose_name='País')),
                ('Prefijo_CIDNI', models.ForeignKey(blank=True, db_column='Prefijo_CIDNI_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='citas.prefijo_cidni', verbose_name='Tipo de ID')),
                ('Sexo', models.ForeignKey(blank=True, db_column='Sexo_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='citas.sexo', verbose_name='Sexo')),
                ('ciudad', models.ForeignKey(blank=True, db_column='id_Ciudad', null=True, on_delete=django.db.models.deletion.SET_NULL, to='citas.ciudad', verbose_name='Ciudad')),
                ('especialidades', models.ManyToManyField(blank=True, through='citas.MedicoEspecialidad', to='citas.especialidadmedica', verbose_name='Especialidades')),
                ('estado', models.ForeignKey(blank=True, db_column='id_Estado', null=True, on_delete=django.db.models.deletion.SET_NULL, to='citas.estado', verbose_name='Estado/Provincia')),
                ('estado_civil', models.ForeignKey(blank=True, db_column='Civil_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='citas.estadocivil', verbose_name='Estado Civil')),
                ('municipio', models.ForeignKey(blank=True, db_column='id_Municipio', null=True, on_delete=django.db.models.deletion.SET_NULL, to='citas.municipio', verbose_name='Municipio')),
                ('parroquia', models.ForeignKey(blank=True, db_column='id_Parroquia', null=True, on_delete=django.db.models.deletion.SET_NULL, to='citas.parroquia', verbose_name='Parroquia')),
            ],
            options={
                'verbose_name': 'Médico',
                'verbose_name_plural': 'Médicos',
                'db_table': 'usuarios_medicos',
                'ordering': ['Apellidos_Medicos', 'Nombres_Medico'],
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='medicoespecialidad',
            name='medico',
            field=models.ForeignKey(db_column='id_Medico', on_delete=django.db.models.deletion.CASCADE, to='citas.usuariomedico'),
        ),
        migrations.CreateModel(
            name='DatosSeniat',
            fields=[
                ('id_Datos_SENIAT', models.AutoField(db_column='id_Datos_SENIAT', primary_key=True, serialize=False)),
                ('RIF', models.CharField(db_column='RIF', max_length=20, unique=True, verbose_name='RIF')),
                ('Direccion', models.TextField(db_column='Direccion', verbose_name='Dirección Fiscal')),
                ('Fecha', models.DateTimeField(auto_now=True, db_column='Fecha', verbose_name='Fecha de Registro')),
                ('razon_social', models.CharField(blank=True, max_length=200, null=True, verbose_name='Razón Social')),
                ('contribuyente_especial', models.BooleanField(default=False, verbose_name='¿Es Contribuyente Especial?')),
                ('nro_licencia', models.CharField(blank=True, max_length=50, null=True, verbose_name='N° de Licencia')),
                ('Medico', models.OneToOneField(blank=True, db_column='Medico_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='datos_seniat', to='citas.usuariomedico', verbose_name='Médico')),
            ],
            options={
                'verbose_name': 'Datos del SENIAT',
                'verbose_name_plural': 'Datos del SENIAT',
                'db_table': 'datos_seniat',
                'ordering': ['Medico__Apellidos_Medicos', 'Medico__Nombres_Medico'],
                'managed': True,
            },
        ),
        migrations.AlterUniqueTogether(
            name='medicoespecialidad',
            unique_together={('medico', 'especialidad')},
        ),
    ]
