# Generated by Django 5.2.7 on 2025-10-20 16:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Consultorio',
            fields=[
                ('id_Consultorio', models.AutoField(db_column='id_Consultorio', primary_key=True, serialize=False)),
                ('Direccion', models.CharField(blank=True, max_length=200, null=True, verbose_name='Dirección')),
                ('numero_consultorio', models.CharField(blank=True, max_length=200, null=True, verbose_name='Número de Consultorio')),
                ('Telefono', models.CharField(blank=True, max_length=20, null=True, verbose_name='Teléfono')),
                ('Celular', models.CharField(blank=True, max_length=20, null=True, verbose_name='Celular')),
                ('Correo', models.EmailField(blank=True, max_length=200, null=True, verbose_name='Correo Electrónico')),
                ('Status', models.BooleanField(default=True, verbose_name='Activo')),
                ('Especialidad_Medica', models.ForeignKey(blank=True, db_column='Especialidad_Medica_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='citas.especialidadmedica', verbose_name='Especialidad Médica')),
                ('ciudad', models.ForeignKey(blank=True, db_column='Ciudad_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='citas.ciudad', verbose_name='Ciudad')),
                ('estado', models.ForeignKey(blank=True, db_column='Estado_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='citas.estado', verbose_name='Estado/Provincia')),
                ('municipio', models.ForeignKey(blank=True, db_column='Municipio_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='citas.municipio', verbose_name='Municipio')),
                ('parroquia', models.ForeignKey(blank=True, db_column='Parroquia_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='citas.parroquia', verbose_name='Parroquia')),
            ],
            options={
                'verbose_name': 'Consultorio',
                'verbose_name_plural': 'Consultorios',
                'db_table': 'consultorios',
                'ordering': ['numero_consultorio'],
            },
        ),
    ]
