# Generated by Django 5.2.7 on 2025-10-20 18:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citas', '0002_consultorio'),
    ]

    operations = [
        migrations.CreateModel(
            name='Turno',
            fields=[
                ('id_Turno', models.AutoField(db_column='id_Turno', primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre del Turno')),
                ('hora_inicio', models.TimeField(verbose_name='Hora de Inicio')),
                ('hora_fin', models.TimeField(verbose_name='Hora de Fin')),
                ('activo', models.BooleanField(default=True, verbose_name='¿Activo?')),
            ],
            options={
                'verbose_name': 'Turno',
                'verbose_name_plural': 'Turnos',
                'db_table': 'turnos',
                'ordering': ['hora_inicio'],
            },
        ),
        migrations.CreateModel(
            name='HorarioCita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domicilio', models.BooleanField(default=False, verbose_name='¿Atención a Domicilio?')),
                ('calendar_event_id', models.CharField(blank=True, max_length=128, null=True, verbose_name='ID del Evento en el Calendario')),
                ('calendar_id', models.CharField(blank=True, max_length=128, null=True, verbose_name='ID del Calendario')),
                ('start_datetime', models.DateTimeField(verbose_name='Fecha y Hora de Inicio')),
                ('end_datetime', models.DateTimeField(verbose_name='Fecha y Hora de Fin')),
                ('recurrence_rule', models.CharField(blank=True, max_length=255, null=True, verbose_name='Regla de Recurrencia')),
                ('activo', models.BooleanField(default=True, verbose_name='¿Activo?')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Última Actualización')),
                ('especialidad', models.ForeignKey(db_column='especialidad_id', on_delete=django.db.models.deletion.CASCADE, related_name='horarios_citas', to='citas.especialidadmedica', verbose_name='Especialidad Médica')),
                ('medico', models.ForeignKey(db_column='medico_id', on_delete=django.db.models.deletion.CASCADE, related_name='horarios_citas', to='citas.usuariomedico', verbose_name='Médico')),
                ('turno', models.ForeignKey(db_column='turno_id', on_delete=django.db.models.deletion.CASCADE, related_name='horarios_citas', to='citas.turno', verbose_name='Turno')),
            ],
            options={
                'verbose_name': 'Horario de Cita',
                'verbose_name_plural': 'Horarios de Citas',
                'db_table': 'horarios_citas',
                'ordering': ['-start_datetime', 'medico'],
                'indexes': [models.Index(fields=['medico', 'especialidad'], name='horarios_ci_medico__1467a7_idx'), models.Index(fields=['start_datetime', 'end_datetime'], name='horarios_ci_start_d_d6f8e0_idx'), models.Index(fields=['activo'], name='horarios_ci_activo_3a0ebe_idx')],
            },
        ),
    ]
