# Generated by Django 5.2.7 on 2025-10-20 18:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('citas', '0003_turno_horariocita'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='turno',
            options={'verbose_name': 'Turno', 'verbose_name_plural': 'Turnos'},
        ),
        migrations.RemoveField(
            model_name='turno',
            name='hora_fin',
        ),
        migrations.RemoveField(
            model_name='turno',
            name='hora_inicio',
        ),
    ]
