# Generated by Django 5.2.7 on 2025-10-20 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citas', '0004_alter_turno_options_remove_turno_hora_fin_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='turno',
            options={'ordering': ['nombre'], 'verbose_name': 'Turno', 'verbose_name_plural': 'Turnos'},
        ),
        migrations.AddField(
            model_name='turno',
            name='hora_fin',
            field=models.TimeField(blank=True, help_text='Formato: HH:MM', null=True, verbose_name='Hora de Fin'),
        ),
        migrations.AddField(
            model_name='turno',
            name='hora_inicio',
            field=models.TimeField(blank=True, help_text='Formato: HH:MM', null=True, verbose_name='Hora de Inicio'),
        ),
    ]
