# Generated by Django 5.2.7 on 2025-10-21 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citas', '0005_alter_turno_options_turno_hora_fin_turno_hora_inicio'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banco',
            fields=[
                ('id_Bancos', models.AutoField(db_column='id_Bancos_Bs', primary_key=True, serialize=False)),
                ('Bancos', models.CharField(db_column='Bancos', max_length=200, verbose_name='Nombre del Banco')),
                ('Activo', models.BooleanField(db_column='Activo', default=True, verbose_name='Activo')),
                ('Codigo_Bancario', models.IntegerField(blank=True, db_column='Codigo_Bancario', null=True, verbose_name='Código Bancario')),
            ],
            options={
                'verbose_name': 'Banco',
                'verbose_name_plural': 'Bancos',
                'db_table': 'bancos',
                'ordering': ['Bancos'],
            },
        ),
    ]
