# Generated by Django 5.2.7 on 2025-10-21 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citas', '0006_banco'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banco',
            name='id_Bancos',
            field=models.AutoField(db_column='id_Bancos', primary_key=True, serialize=False),
        ),
    ]
