# Generated by Django 5.2.7 on 2025-10-23 04:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("citas", "0007_alter_banco_id_bancos"),
    ]

    operations = [
        migrations.CreateModel(
            name="CitasReservadas",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "calendar_event_id",
                    models.CharField(
                        blank=True,
                        help_text="ID del evento en Google Calendar",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "start_datetime",
                    models.DateTimeField(help_text="Hora de inicio de la cita"),
                ),
                (
                    "end_datetime",
                    models.DateTimeField(help_text="Hora de fin de la cita"),
                ),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("pendiente", "Pendiente"),
                            ("confirmada", "Confirmada"),
                            ("completada", "Completada"),
                            ("cancelada", "Cancelada"),
                            ("no_asistio", "No Asistió"),
                        ],
                        default="pendiente",
                        help_text="Estado actual de la cita",
                        max_length=20,
                    ),
                ),
                (
                    "nota",
                    models.TextField(
                        blank=True,
                        help_text="Notas adicionales sobre la cita",
                        null=True,
                    ),
                ),
                (
                    "costo",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Costo de la consulta",
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Fecha y hora de creación del registro",
                    ),
                ),
                (
                    "horario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="citas_reservadas",
                        to="citas.horariocita",
                    ),
                ),
                (
                    "paciente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="citas_reservadas",
                        to="citas.paciente",
                    ),
                ),
            ],
            options={
                "verbose_name": "Cita Reservada",
                "verbose_name_plural": "Citas Reservadas",
                "db_table": "citas_reservadas",
                "ordering": ["start_datetime"],
            },
        ),
    ]
