# Generated by Django 5.2.7 on 2025-10-15 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='paciente',
            options={'ordering': ['apellido', 'nombre'], 'verbose_name': 'Paciente', 'verbose_name_plural': 'Pacientes'},
        ),
        migrations.RemoveField(
            model_name='paciente',
            name='edad',
        ),
        migrations.AddField(
            model_name='paciente',
            name='activo',
            field=models.BooleanField(default=True, verbose_name='Activo'),
        ),
        migrations.AddField(
            model_name='paciente',
            name='alergias',
            field=models.TextField(blank=True, help_text='Lista de alergias conocidas', null=True, verbose_name='Alergias'),
        ),
        migrations.AddField(
            model_name='paciente',
            name='ciudad',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Ciudad'),
        ),
        migrations.AddField(
            model_name='paciente',
            name='codigo_postal',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Código Postal'),
        ),
        migrations.AddField(
            model_name='paciente',
            name='contacto_emergencia',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Contacto de Emergencia'),
        ),
        migrations.AddField(
            model_name='paciente',
            name='enfermedades_cronicas',
            field=models.TextField(blank=True, null=True, verbose_name='Enfermedades Crónicas'),
        ),
        migrations.AddField(
            model_name='paciente',
            name='estado',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Estado'),
        ),
        migrations.AddField(
            model_name='paciente',
            name='estado_civil',
            field=models.CharField(blank=True, choices=[('S', 'Soltero/a'), ('C', 'Casado/a'), ('D', 'Divorciado/a'), ('V', 'Viudo/a'), ('U', 'Unión libre')], max_length=1, null=True, verbose_name='Estado Civil'),
        ),
        migrations.AddField(
            model_name='paciente',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='pacientes/fotos/', verbose_name='Fotografía'),
        ),
        migrations.AddField(
            model_name='paciente',
            name='medicamentos',
            field=models.TextField(blank=True, help_text='Medicamentos actuales', null=True, verbose_name='Medicamentos'),
        ),
        migrations.AddField(
            model_name='paciente',
            name='numero_seguro',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Número de Seguro'),
        ),
        migrations.AddField(
            model_name='paciente',
            name='observaciones',
            field=models.TextField(blank=True, null=True, verbose_name='Observaciones'),
        ),
        migrations.AddField(
            model_name='paciente',
            name='ocupacion',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Ocupación'),
        ),
        migrations.AddField(
            model_name='paciente',
            name='seguro_medico',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Compañía de Seguro'),
        ),
        migrations.AddField(
            model_name='paciente',
            name='telefono_emergencia',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Teléfono de Emergencia'),
        ),
        migrations.AddField(
            model_name='paciente',
            name='tipo_sangre',
            field=models.CharField(blank=True, choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], max_length=3, null=True, verbose_name='Tipo de Sangre'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='apellido',
            field=models.CharField(max_length=100, verbose_name='Apellidos'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='direccion',
            field=models.TextField(blank=True, null=True, verbose_name='Dirección'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Correo Electrónico'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='fecha_egreso',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de Egreso'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='fecha_ingreso',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Ingreso'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='fecha_nacimiento',
            field=models.DateField(verbose_name='Fecha de Nacimiento'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='genero',
            field=models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino'), ('O', 'Otro'), ('N', 'No especificado')], default='N', max_length=1, verbose_name='Género'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='nombre',
            field=models.CharField(max_length=100, verbose_name='Nombres'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='telefono',
            field=models.CharField(max_length=15, verbose_name='Teléfono'),
        ),
        migrations.AddIndex(
            model_name='paciente',
            index=models.Index(fields=['apellido', 'nombre'], name='index_pacie_apellid_eb6800_idx'),
        ),
        migrations.AddIndex(
            model_name='paciente',
            index=models.Index(fields=['fecha_ingreso'], name='index_pacie_fecha_i_9a5151_idx'),
        ),
    ]
